/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppLojaRouteImport } from './routes/_app.loja'
import { Route as AppIndicacoesRouteImport } from './routes/_app.indicacoes'
import { Route as AppExtratoRouteImport } from './routes/_app.extrato'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppCampanhasIdRouteImport } from './routes/_app.campanhas.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppLojaRoute = AppLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicacoesRoute = AppIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCampanhasIdRoute = AppCampanhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampanhasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/campanhas': typeof AppCampanhasRouteWithChildren
  '/extrato': typeof AppExtratoRoute
  '/indicacoes': typeof AppIndicacoesRoute
  '/loja': typeof AppLojaRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/campanhas/$id': typeof AppCampanhasIdRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/campanhas': typeof AppCampanhasRouteWithChildren
  '/extrato': typeof AppExtratoRoute
  '/indicacoes': typeof AppIndicacoesRoute
  '/loja': typeof AppLojaRoute
  '/perfil': typeof AppPerfilRoute
  '/ranking': typeof AppRankingRoute
  '/': typeof AppIndexRoute
  '/campanhas/$id': typeof AppCampanhasIdRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/campanhas': typeof AppCampanhasRouteWithChildren
  '/_app/extrato': typeof AppExtratoRoute
  '/_app/indicacoes': typeof AppIndicacoesRoute
  '/_app/loja': typeof AppLojaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campanhas/$id': typeof AppCampanhasIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/campanhas'
    | '/extrato'
    | '/indicacoes'
    | '/loja'
    | '/perfil'
    | '/ranking'
    | '/campanhas/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/campanhas'
    | '/extrato'
    | '/indicacoes'
    | '/loja'
    | '/perfil'
    | '/ranking'
    | '/'
    | '/campanhas/$id'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/campanhas'
    | '/_app/extrato'
    | '/_app/indicacoes'
    | '/_app/loja'
    | '/_app/perfil'
    | '/_app/ranking'
    | '/_app/'
    | '/_app/campanhas/$id'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loja': {
      id: '/_app/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AppLojaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indicacoes': {
      id: '/_app/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AppIndicacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extrato': {
      id: '/_app/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/campanhas/$id': {
      id: '/_app/campanhas/$id'
      path: '/$id'
      fullPath: '/campanhas/$id'
      preLoaderRoute: typeof AppCampanhasIdRouteImport
      parentRoute: typeof AppCampanhasRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppCampanhasRouteChildren {
  AppCampanhasIdRoute: typeof AppCampanhasIdRoute
}

const AppCampanhasRouteChildren: AppCampanhasRouteChildren = {
  AppCampanhasIdRoute: AppCampanhasIdRoute,
}

const AppCampanhasRouteWithChildren = AppCampanhasRoute._addFileChildren(
  AppCampanhasRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCampanhasRoute: typeof AppCampanhasRouteWithChildren
  AppExtratoRoute: typeof AppExtratoRoute
  AppIndicacoesRoute: typeof AppIndicacoesRoute
  AppLojaRoute: typeof AppLojaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingRoute: typeof AppRankingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCampanhasRoute: AppCampanhasRouteWithChildren,
  AppExtratoRoute: AppExtratoRoute,
  AppIndicacoesRoute: AppIndicacoesRoute,
  AppLojaRoute: AppLojaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingRoute: AppRankingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
